=== bstansberry/JBossAS_5_1_EDG/testsuite/src/resources/cc/ccTsfiMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://www.redhat.com/CcTsfiMap"
            targetNamespace="http://www.redhat.com/CcTsfiMap"
>
  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     Schema for mapping document between test (test suite, test case) and TSFI.
     This mapping is created for purpose of Common Criteria evaluation of JBoss AS.
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="testCaseMapping" type="TestCaseMappingType">
  <!-- Tes suite name has to be unique, so we are enforcing it. -->    
    <xsd:unique name="testSuiteNameUnique">
      <xsd:selector xpath="testSuite"/>
        <xsd:field    xpath="@name"/>
    </xsd:unique>  
  </xsd:element>
  
  <xsd:complexType name="TestCaseMappingType">
    <xsd:sequence>
      <xsd:element name="testSuite" type="TestSuiteType" minOccurs="1" maxOccurs="unbounded">
      
        <xsd:unique name="testCaseNameUnique">
          <xsd:selector xpath="testCase"/>
          <xsd:field    xpath="@name"/>
        </xsd:unique>  
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="TestSuiteType">
    <xsd:sequence>
      <xsd:element name="desc" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="testCase" type="TestCaseType" minOccurs="1" maxOccurs="unbounded">
        <xsd:unique name="testNameUnique">
          <xsd:selector xpath="test"/>
          <xsd:field    xpath="@name"/>
        </xsd:unique>  
      </xsd:element>  
    </xsd:sequence>
    <xsd:attribute name="name" type="TestSuiteName" use="required"/>
  </xsd:complexType>  
  
  <!-- Enumeration of all possible test suite names -->
  <xsd:simpleType name="TestSuiteName">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="EAP"/>   <!-- EAP test suite -->
      <xsd:enumeration value="CTS"/>   <!-- J2EE TCK 1.4 test suite -->
      <xsd:enumeration value="EJB3"/>  <!-- EJB3 project test suite -->
      <xsd:enumeration value="JBM"/>   <!-- JBoss Messaging project test suite -->
      <xsd:enumeration value="JBWS"/>  <!-- JBoss Webservices project test suite -->
   </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:complexType name="TestCaseType">
    <xsd:sequence>
      <xsd:element name="desc" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="test" type="TestType" minOccurs="1" maxOccurs="unbounded"/>     
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>  
  
  <xsd:complexType name="TestType">
    <xsd:sequence>
      <xsd:element name="desc" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="TSFI" type="xsd:string" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/> 
  </xsd:complexType>
</xsd:schema>

=== bstansberry/JBossAS_5_1_EDG/testsuite/src/resources/cc/testCaseMapping_2.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Test Case Mapping for EAP 5.1 Common Criteria Certification
  ===========================================================
  
  Note: 
  - TSFi master data can be fund in latest version of CC_Test_Plan_EAP_5.1.pdf in chapter "3.1 TSFI Id Master Data"

-->
<cc:testCaseMapping xmlns:cc="http://www.redhat.com/CcTsfiMap"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.redhat.com/CcTsfiMap ccTsfiMap.xsd"
>

  <!-- Standard EAP testsuite to TOE Security Functionality Interface mapping -->
  <testSuite name="EAP">
    <testCase name="org.jboss.test.security.test.CallerInfoUnitTestCase">
      <desc>Tests of the caller context state</desc>
      <test name="testCallerSubject">
        <desc>Test Objective: Test return of a custom principal from getCallerPrincipal.
                              Call a method on the ejb/StatelessSession, ejb/StatefulSession, ejb/Entity
                              ejb-refs and validate that the security context seen after each call
                              matches the expected context seen at the start of the call.
              Expected Result: Security context after each call type must contain expected principal pushed to the custom princials
                               before the call.  
        </desc>
        <TSFI>tsfi.port.rmi.jrmp</TSFI>
        <TSFI>tsfi.app.ejb-jar.xml</TSFI>
        <TSFI>tsfi.app.jboss.xml</TSFI>
      </test>
    </testCase>
    <testCase name="org.jboss.test.deployers.web.test.WEBDeploymentUnitTestCase">
      <desc></desc>
      <test name="testWEBDeployment">
        <TSFI>tsfi.app.web.xml</TSFI>
      </test>
    </testCase>
    <testCase name="org.jboss.test.security.test.SubjectContextUnitTestCase">
      <desc>Tests of the JACC subject policy context handler state and consistency with the container caller principal, isCallerInRole methods.</desc>
      <test name="testUserMethodViaServlet">
        <desc>Test Objective: Test if calling userMethod via servlet has caller principal equal to one we called the method with.
                              Test if caller has proper roles assigned.
                              Tests if policy subject contains proper roles.
                              Tests if run as identity works for subsequent call to session bean. 
              Expected Result: Run without exceptions and http request finishes with HTTP_OK status. 
        </desc>
        <TSFI>tsfi.port.web.http</TSFI>
     </test>
    </testCase>
    <testCase name="org.jboss.test.security.test.DeepCopySubjectUnitTestCase">
      <desc>JBAS-2657: Add option to deep copy the authenticated subject sets
    
    Testcase that unit tests the cloneability of various JBossSX 
    Principal/Groups
    Also does a test of the serverside Subject deep copy via a mutable
    Principal</desc>
      <test name="testSubjectCloning">
        <desc>Test Objective: Test the Deep Copy of Subjects by the JaasSecurityManager via a test servlet deployed.
              Expected Result: Run without exceptions and with proper HTTP result after each of three different calls.
        </desc>
        <TSFI>tsfi.port.web.http</TSFI>
      </test>
    </testCase>
    <testCase name="org.jboss.test.security.test.EJB3SpecUnitTestCase">
    	<desc></desc>
    	<test name="testAdministratorMethodAccess">
    		<desc></desc>
    		<TSFI>tsfi.ann.DenyAll</TSFI>
    		<TSFI>tsfi.ann.PermitAll</TSFI>
    		<TSFI>tsfi.ann.RolesAllowed</TSFI>
    	</test>
    	<test name="testRegularUserMethodAccess">
    		<desc></desc>
    		<TSFI>tsfi.ann.DenyAll</TSFI>
    		<TSFI>tsfi.ann.PermitAll</TSFI>
    		<TSFI>tsfi.ann.RolesAllowed</TSFI>
    	</test>
    	<test name="testGuestMethodAccess">
    		<desc></desc>
    		<TSFI>tsfi.ann.DenyAll</TSFI>
    		<TSFI>tsfi.ann.PermitAll</TSFI>
    		<TSFI>tsfi.ann.RolesAllowed</TSFI>
    	</test>
    	<test name="testUnauthenticatedMethodAccess">
    		<desc></desc>
    		<TSFI>tsfi.ann.DenyAll</TSFI>
    		<TSFI>tsfi.ann.PermitAll</TSFI>
    		<TSFI>tsfi.ann.RolesAllowed</TSFI>
    	</test>
    	<test name="testRunAsMethodAccess">
    		<desc></desc>
    		<TSFI>tsfi.ann.RunAs</TSFI>
    		<TSFI>tsfi.ann.RolesAllowed</TSFI>
    	</test>
    </testCase>
    <testCase name="org.jboss.test.ejb3.jbpapp2473.unit.RunAsUnitTestCase">
      <desc></desc>
      <test name="testRole1">
        <desc></desc>
        <TSFI></TSFI>
      </test>
      <test name="testRole2">
        <desc></desc>
        <TSFI>tsfi.ann.RunAsPrincipal</TSFI>
      </test>
      <test name="testRunAsManager">
        <desc></desc>
        <TSFI></TSFI>
      </test>
      <test name="testRunAsPrincipal">
        <desc></desc>
        <TSFI>tsfi.ann.RunAsPrincipal</TSFI>
      </test>
    </testCase>
    <testCase name="org.jboss.test.security.test.EJBSpecUnitTestCase">
      <desc>Test of EJB spec conformace using the security-spec.jar deployment unit. These test the basic role based access model.</desc>
      <test name="testSecurityDomain">
        <desc>Test Objective: Validate that the users have the expected logins and roles.
                               Tests following if user has correct password, correct role, user cannot call method using bad password.
                               Tests same cases for use with different security domain.
              Expected Result: All assertions after call has to be fulfilled and there is no exception thrown during execution. 
        </desc>
        <TSFI>tsfi.jmx.rmi</TSFI>
      </test>
      <test name="testStatefulCreateCaller">
        <desc>Test Objective: Test the use of getCallerPrincipal from within the ejbCreate in a stateful session bean.
              Expected Result: Finish the test without exceptions indicating successful use of getCallerPrincipal. 
        </desc>
        <TSFI>tsfi.port.rmi.jrmp</TSFI>
      </test>
      <test name="testGetCallerPrincipal">
        <desc>Test Objective:
    1. SecureBean returns a non-null principal when getCallerPrincipal
       is called with a security context and that this is propagated
       to its Entity bean ref.
    
    2. UnsecureBean throws an IllegalStateException when getCallerPrincipal
       is called without a security context.
              Expected Result: 1. Return caller principal which is equal to the one of callee.  
                               2. Throw RemoteException on unsecured session bean which. 
        </desc>
        <TSFI>tsfi.port.rmi.jrmp</TSFI>
      </test>
      <test name="testDomainInteraction">
        <desc>Test Objective: Test that a call interacting with different security domains does not change the roles it had before the call.
              Expected Result: Test has to finish without any exception.       
        </desc>
        <TSFI>tsfi.port.rmi.jrmp</TSFI>
      </test>
      <test name="testPrincipalPropagation">
        <desc>Test Objective: Test that the calling principal is propagated across bean calls.
              Expected Result: Test has to finish without any exception.       
        </desc>
        <TSFI>tsfi.port.rmi.jrmp</TSFI>
      </test>
      <test name="testMethodAccess">
        <desc>Test Objective: Test that the echo method is accessible by an Echo
                              role. Since the noop() method of the StatelessSession
                              bean was not assigned any permissions it should be unchecked.
              Expected Result: Test has to finish without any exception.       
        </desc>
        <TSFI>tsfi.port.rmi.jrmp</TSFI>
      </test>
      <test name="testDomainMethodAccess">
        <desc>Test Objective: Test that the echo method is accessible by an Echo
                              role. Since the excluded() method of the StatelessSession
                              bean has been placed into the excluded set it should not
                              accessible by any user. This uses the security domain of the
                              JaasSecurityDomain service to test its use as an authentication mgr.
              Expected Result: Test has to finish without any exception.       
        </desc>
        <TSFI>tsfi.port.rmi.jrmp</TSFI>
      </test>
      <test name="testMethodAccess2">
        <desc>Test Objective: Test that the permissions assigned to the stateless session bean:
                              with ejb-name=org/jboss/test/security/ejb/StatelessSession_test
                              are read correctly.
              Expected Result: Test has to finish without any exception.       
        </desc>
        <TSFI>tsfi.port.rmi.jrmp</TSFI>
      </test>
      <test name="testLocalMethodAccess">
        <desc>Test Objective: Test a user with Echo and EchoLocal roles can access the CalleeBean
                              through its local interface by calling the CallerBean and that a user
                              with only a EchoLocal cannot call the CallerBean.
              Expected Result: Test has to finish without any exception.       
        </desc>
        <TSFI>tsfi.port.rmi.jrmp</TSFI>
      </test>
      <test name="testUncheckedRemote">
        <desc>Test Objective: Test access to a bean with a mix of remote interface permissions and unchecked permissions with the unchecked permissions declared first.
              Expected Result: Unchecked remote access has to pass without exception and exluded() method call should throw RemoteException. 
        </desc>
        <TSFI>tsfi.port.rmi.jrmp</TSFI>
      </test>
      <test name="testRemoteUnchecked">
        <desc>Test Objective: Test access to a bean with a mix of remote interface permissions and unchecked permissions with the unchecked permissions declared last.
              Expected Result: Unchecked remote access has to pass without exception and exluded() method call should throw RemoteException. 
        </desc>
        <TSFI>tsfi.port.rmi.jrmp</TSFI>
